### ISSUE TITLE
Feature request: allow type=0

### ISSUE THREAD

**Issue by sTeamTraen** [daattali/shinycssloaders#15]
This is indeed just a "WIBNI" (Wouldn't It Be Nice If...), but: it would be nice to allow the spinner type to be set to zero, which would display no spinner.

**Comment by andrewsali** [comment]
This sounds like a reasonable proposition, would you be interested in submitting a pull-request?

**Comment by sTeamTraen** [comment]
Very possibly, if I knew what a pull request was and what it involved me doing. I have 43 years of programming experience (if you want something doing in SNOBOL4, RTL/2, or RSX-11M assembler, I'm your man), and absolutely zero knowledge of Git. I will go and RTFM, or at least RTF beginner's guide.

**Comment by daattali** [comment]
I also like this idea, having 0 mean "nothing" is good design IMO. Thanks for the pull request (and for RTFM!), your changes should be merged soon

**Comment by daattali** [comment]
This is solved by https://github.com/daattali/shinycssloaders/pull/18 - thanks
