### ISSUE TITLE
Vertical centering of Type 7 spinner is not perfect

### ISSUE THREAD

**Issue by andrewsali** [daattali/shinycssloaders#2]

**Comment by daattali** [comment]
It looks like perhaps adding a css rule to the loader

```
top: <18.75*size>px
```

would solve this. I'm not intimately familiar with all the parameters and usecases so perhaps this doesn't always work, but it seems promising

**Comment by daattali** [comment]
Not enough of a problem to warrant an issue, we'll live with this
