### ISSUE TITLE
custom.css example?

### ISSUE THREAD

**Issue by ldecicco-USGS** [daattali/shinycssloaders#21]
I have a graph that is really tall. I'd like to move the spinner to the top instead of the center (it gets lost in the center). I've tried:
```
withSpinner(plotOutput("endpointGraph", height = height, width = "100%"),
                     custom.css = "vertical-align:top")
```
and
```
withSpinner(plotOutput("endpointGraph", height = height, width = "100%"),
                     custom.css = "vertical-align: top;")
```

But that gives me an error "invalid argument type". Do you have any examples of how to use the `custom.css` argument?

**Comment by trafficonese** [comment]
Try with this:

`withSpinner(plotOutput(outputId = "distPlot"), custom.css = "vertical-align: top; top: 0%;")`

Or just `custom.css = "top: 0%;"` should be fine too.

**Comment by tonyk7440** [comment]
Getting this error also with:

`withSpinner(imageOutput(outputId = "wordcloud"), custom.css = "top: 0%;")
`

Error:
`Warning: Error in !: invalid argument type
  73: withSpinner`

**Comment by emmacooperpeterson** [comment]
I'd also love to see an example of how to use `custom.css` – can't seem to get anything to work 😞  @andrewsali

**Comment by daattali** [comment]
The `custom.css` option takes a TRUE or FALSE, just to tell the package if to add its own CSS or not.

The actual CSS you want to add needs to go in your app's ui. The function now accepts an `id` parameter so that you can target specific spinners in your CSS
