### ISSUE TITLE
Tabs prevent spinner from showing during recalculation

### ISSUE THREAD

**Issue by kornl** [daattali/shinycssloaders#24]
Tabs can prevent the spinner from showing during recalculation. Here is an example:

```
library(shinycssloaders)

ui <- fluidPage(
  navbarPage(
    title="Menu",
    tabPanel("Tab 1",
      sliderInput(inputId = "bins", 
        label = "Number of bins:", min = 1, max = 50, value = 30)
    ),
    tabPanel("Tab 2", withSpinner(plotOutput(outputId = "distPlot"))
    )
  )
)

server <- function(input, output) {
  output$distPlot <- renderPlot({
    Sys.sleep(3)
    x    <- faithful$waiting
    bins <- seq(min(x), max(x), length.out = input$bins + 1)
    hist(x, breaks = bins, xlab = "Waiting time [min]")
  })
}

shinyApp(ui, server)
```

The first time _Tab 2_ is visited the spinner is shown. But if afterwards the slider input on _Tab 1_ is changed and _Tab 2_ visited again the spinner is not shown during recalculation.

**Comment by DrNathanLi** [comment]
Hi @kornl,

I am wondering whether you find any method to solve this issue. Thanks a lot.

Hi @andrewsali 

I have the same issue. Is there any method to solve this? Thanks a lot.

**Comment by kornl** [comment]
No. (For my app I added a progress bar and it was therefore obvious that there are still calculations done, even if no spinner is shown during recalculation.) Would still be interested in a fix.

**Comment by ayushikachhara** [comment]
Would be interested in a fix for this please

**Comment by daattali** [comment]
I tried your code and it works - it was fixed at some point in the past few months. If you think there's still bugs, feel free to open a new issue
