### ISSUE TITLE
Suggestion: Add message option

### ISSUE THREAD

**Issue by philippnkling** [daattali/shinycssloaders#28]
Hello, 

I am really content with the Spinner options to display while rendering a page. However, I would really like to have an option to show a message in addition to the Spinner image, as the loading of the page might take some time. Other alternatives such as `withProgress()` (https://shiny.rstudio.com/articles/progress.html) seem to have this feature and I think this might enrich the Spinner application very much. What do you think? Did you find a workaround?

**Comment by daattali** [comment]
If you can think of a good UI for this that would be robust to all cases, then a PR would be great

**Comment by laurenmarietta** [comment]
I would also love this feature! Currently working on a Shiny app that takes a while to load at startup, and would love in particular to have an initial loading message like "Loading data, please wait about 20 seconds..." and perhaps a simpler "Recalculating..." message for future loads after startup.

Without having looked into the shinycssloaders code, I imagine this could be achieved by adding another div to hold some text beneath the loader?

**Comment by jjalcolea** [comment]
Yep. I was looking exactly for this feature... :+1:

**Comment by daattali** [comment]
This is being worked on in https://github.com/daattali/shinycssloaders/pull/72

**Comment by daattali** [comment]
Solved with #72 

You can use the `caption` parameter. It accepts either text (`caption = "Please wait"`) or HTML (`caption = div(strong("Loading"), br(), "Please wait")`)
