### ISSUE TITLE
withSpinner not reloading with dashboardpage

### ISSUE THREAD

**Issue by albertobettini** [daattali/shinycssloaders#29]
Hi,

I am using withSpinner with dashboardpage and I have the following problem.

I have two different tabitems:

the first has a selectInput object
the second has a plot depending on the first.

the loading spinner appears only the first time the plot is calculated, therefore if i go back to the first page and change the value in the selectinput when i return to the plot page the spinner does not apper.

Can someone help me?

Thankyou

**Comment by ayushikachhara** [comment]
I have the exact same issue with my app. Has there been an update on this issue yet?

**Comment by daattali** [comment]
A similar issue was opened last year and I just tried the code from there and it was resolved.

I'm closing this issue, assuming it's the same resolved issue. If you still have problems, feel free to open a new issue, but please include code sample.
