### ISSUE TITLE
Suggestion: using more unique name than "assets" for client resource path

### ISSUE THREAD

**Issue by lawrencecrane** [daattali/shinycssloaders#30]
shinycssloaders package currently adds/overwrites resource path "assets" (in R/globals.R). As this is quite generic path that Shiny apps themselves might want to use to store their assets/static content, then this package is not "compatible" with those.

Basically just a suggestion that could this be switched to more unique name, for example, shinycssloaders -- rather than assets?

**Comment by daattali** [comment]
I also noticed this https://github.com/daattali/shinycssloaders/issues/48 and fixed it last week.
