### ISSUE TITLE
withSpinner is hidden when hosting app on port 80

### ISSUE THREAD

**Issue by ismirsehregal** [daattali/shinycssloaders#44]
Using the following code under Windows7 x64 with Chrome doesn't display a spinner when executed via `source()`:

```
library(shiny)
library(shinycssloaders)

ui <- fluidPage(
  withSpinner(uiOutput("dummyid"))
)

server = function(input, output, session){
  output$dummyid <- renderUI({
    Sys.sleep(5)
    "result"
  })
}

app <- shinyApp(ui, server)
runApp(app, host ="0.0.0.0", port = 80, launch.browser = TRUE) # causes hidden spinner

```

![screen](https://user-images.githubusercontent.com/36849480/74520254-742a6900-4f17-11ea-93fe-5cfc7a560898.gif)

This however worked without problems with shinycssloaders version 0.2.0.

**Comment by ismirsehregal** [comment]
@daattali I just realized, that this behaviour is limited to port 80. After changing the port it's working on my Windows 7 machine.

**Comment by daattali** [comment]
I just tested on windows 7 machine with chrome, on port 80 - your exact code. I cannot reproduce. 

This is extremely strange. If you change `80` to any other number it works? I really wish I could reproduce so I can look into this, it makes no sense to me.

**Comment by ismirsehregal** [comment]
Yes, I changed from `80` to a different port and the spinner was showing up.

I tried deleting all R related firewall settings - no success. But on the other hand the whole web page shouldn't show up if the firewall settings were the issue. Is there any other information I can provide you with? I'm back on this PC on monday.

**Comment by daattali** [comment]
See if you can replicate this on any other machine if possible. I'm so
curious about this issue.

**Comment by ismirsehregal** [comment]
Today (same PC as before) I'm no longer able to reproduce the issue I was showing in the GIF. I'm quite confused, however, I'm closing this, as I was able to make things work again in all my apps.

**Comment by ismirsehregal** [comment]
Something is still going wrong here, just tested one of my apps (now again using `withSpinner()` on Ubuntu - here the spinner is alway shown and I'm getting:

![image](https://user-images.githubusercontent.com/36849480/74645174-b6ea7c00-5177-11ea-83ba-ba3d931057df.png)

**Comment by daattali** [comment]
Is that using the latest github version?

**Comment by ismirsehregal** [comment]
You are right 🙈... I didn' properly reload the package after installing the latest dev version on ubuntu.From my side using the dev version, everything is fine - thanks for your effort!
null

**Comment by ismirsehregal** [comment]
[This](https://stackoverflow.com/questions/60323834/shinyapp-works-but-runapp-doesnt-r) seems to be related.

**Comment by daattali** [comment]
Thanks , that makes me feel better because that guy isn't using this package and still ran into the problem. Seems like a shiny issue. You should maybe open an issue on shiny's repo and link to this and to the SO thread so they'll see how weird and non deterministic this is
