### ISSUE TITLE
Show custom image when loading?

### ISSUE THREAD

**Issue by wfjvdham** [daattali/shinycssloaders#46]
Would it not be a nice feature if users can pass their own image file to display when loading? Or is this implemented somewhere already?

**Comment by daattali** [comment]
Looks like there's a package that extends this one https://github.com/emitanaka/shinycustomloader

**Comment by daattali** [comment]
@wfjvdham I've implemented this in https://github.com/daattali/shinycssloaders/commit/f88445160f0286823db014db72f92087ad1a2c7f

You can use `withCustomSpinner()` instead of `withSpinner()`. Please test and let me know if it works as expected.

**Comment by daattali** [comment]
Update: instead of `withCustomSpinner()`, I changed it so that you still use `withSpinner()` with an `image` parameter

**Comment by wfjvdham** [comment]
Nice! I like it

**Comment by learning-freak** [comment]
Hello, how to set up image path with `image` parameter in oder to use custom image ?
`withSpinner(plotlyOutput("myplot"), image = "how to setp up path to custom image ?")`
