### ISSUE TITLE
CSS Loader Animations fail on deployment to AWS EC2 instance

### ISSUE THREAD

**Issue by erstearns** [daattali/shinycssloaders#47]
What a great package! I just added it to one of my apps and successfully deployed to shinyapps.io to test, but when I deployed to the production version hosted on an AWS EC2 instance, it failed. I am not the server admin for the EC2 instance but am trying to help debug. Is there a list of dependencies(libraries and packages) available? Any previous issues encountered with deployment to non-shinyapps.io servers?

Thank you for all your work in putting this together.

**Comment by daattali** [comment]
The list of required packages should be in the DESCRIPTION file, and they should all be installed automatically when the package is installed. I haven't heard of any issues that happen specifically when deploying, sorry. Usually with issues that only appear when deployed somewhere (not just with this package but in general) it's best to try to see if there's any information in the javascript console or in the error logs of the server.

**Comment by erstearns** [comment]
Thanks for the prompt reply and the direction!
