### ISSUE TITLE
Require double clicking on buttons

### ISSUE THREAD

**Issue by ocelhay** [daattali/shinycssloaders#50]
On several different platforms (R 3.6.3 on Windows, macOS), this shiny app https://github.com/ocelhay/como will works as expected using shinycssloaders v2.0 (https://github.com/daattali/shinycssloaders/commit/279f02998ac193307b9993846ab68856817f06de) but requires double clicking on buttons (e.g. Run Baseline) in order to see results when using shinycssloaders following commit (https://github.com/daattali/shinycssloaders/commit/8ed49e125a2baa402851a942f1034f36b33d7917).

**Comment by daattali** [comment]
Hi @ocelhay, if you believe there's a bug, please create and share a minimal reproducible example that shows the issue.

**Comment by daattali** [comment]
Great, sounds like you're getting closer to a small reprex, thanks!

**Comment by daattali** [comment]
@ocelhay have you been able to get a small reproducible example?

**Comment by ocelhay** [comment]
@daattali couldn't find the time to create one. Sorry for this. Better close it for now.
