### ISSUE TITLE
Unexpected behaviour of withSpinner() when used on valueBoxOutput()

### ISSUE THREAD

**Issue by DmitriiIshutin** [daattali/shinycssloaders#55]
I tried to use `withSpinner()` on a `valueBoxOutput()` object of width 3 (i.e. one quarter of my row width), however for some reason the spinner did not appear above the assigned `valueBoxOutput()` object. Rather, it occupied the entire row. So, with 4 value boxes in a row, I was expecting to see 4 spinners in a row -- each in the same position as my value box. However, I got 4 rows, one spinner in each row, instead.

Could you please help with this?

**Comment by daattali** [comment]
I think this is the same as https://github.com/daattali/shinycssloaders/issues/25 - would you agree? It essentially boils down to the same issue: a spinner always takes up an entire row and is not able to be displayed inline (inline = not the entire width)

**Comment by DmitriiIshutin** [comment]
Thank you for your reply. Yes, both issues are pretty similar.
