### ISSUE TITLE
Manually start/stop the loader for an output element

### ISSUE THREAD

**Issue by Prashanthreddya** [daattali/shinycssloaders#56]
Hi, 

Is it possible to manually start or stop the loader for an output element using shinycssloaders ?
I tried doing this by assigning the corresponding output element with NULL. 

`output$element <- NULL`

This works in the usual scenario. But I am using multiprocessing to fetch data for each element in parallel by using the future module, that is causing the loaders to go off sync when the elements are being rendered. 

Recording of how the component & loader come up while running it sequentially (this is the expected behaviour):
![sequential](https://user-images.githubusercontent.com/14885699/94180439-a0e62c00-febb-11ea-810e-0d9ef81a5fc0.gif)

Recording of how the component & loader come up while using multiprocessing:
![parallel](https://user-images.githubusercontent.com/14885699/94180412-9a57b480-febb-11ea-992a-64a73a7653f7.gif)

**Comment by daattali** [comment]
No, that's not possible with shinycssloaders. This package is explicitly designed to be used in the opposite case - to automatically show when an output is recalculating. If you want to do it manually, you'll need to do it with custom css/javascript (you can use these two examples to help you [1](https://github.com/daattali/advanced-shiny/tree/master/plot-spinner) [2](https://github.com/daattali/advanced-shiny/tree/master/busy-indicator)

**Comment by avsdev-cw** [comment]
I keep bumping into this myself and keep coming across this issue, so I'm going to leave a memorandum here:

Combine shinycssloaders with shinyjs and manually control the loading:
```R
# To hide:
shinyjs::runjs(paste0("$('#", session$ns("SOME_ID_HERE"), "').trigger('shiny:outputinvalidated')"))
# To show:
shinyjs::runjs(paste0("$('#", session$ns("SOME_ID_HERE"), "').trigger('shiny:value')"))
```
Yes, this triggers some internal events which only shiny should be generating, but I've yet to come across any issues with any libraries I am using that triggering events in this manner cause issues with.

**Comment by daattali** [comment]
A lot of packages and custom applications are using these shiny events, it should be fairly safe 👍

**Comment by daattali** [comment]
Since this is a commonly requested feature, I'm re-opening the issue in case someone wants to contribute a PR.

I'd be happy to accept a PR if (a) the code is minimal and clean, and (b) the API for it is straightforward such that the following would work:

```
  shinyApp(
    ui = fluidPage(
      actionButton("recalculate", "Recalculate"),
      actionButton("show", "Show spinner"),
      actionButton("hide", "Hide spinner"),
      withSpinner(plotOutput("plot"))
    ),
    server = function(input, output) {
      output$plot <- renderPlot({
        # This is the normal shinycssloaders behaviour
        input$recalculate
        Sys.sleep(1.5)
        plot(runif(10))
      })
    }

    # This is the new functionality
    observeEvent(input$show, { 
      shinycssloaders::show_spinner("plot")
    })
    observeEvent(input$hide, { 
      shinycssloaders::hide_spinner("plot")
    })
  )
```

**Comment by bitowaqr** [comment]
It would be great to have a js solution for this. The `Sys.sleep(1.5)` causes a bit of a delay for everyone who is using the app if you are running it on a shiny open source server.

**Comment by daattali** [comment]
The sys.sleep was not a solution, it's to create a test. There is no current solution, but yes it would need to be done in javascript.

**Comment by avsdev-cw** [comment]
Seems to be working well for me
