### ISSUE TITLE
Set up custom image path

### ISSUE THREAD

**Issue by learning-freak** [daattali/shinycssloaders#57]
Hello, let assume we have an image named `mypic.gif` in a folder named `myfolder`.
how to set up image path with `image` parameter in oder to use custom image ?
`withSpinner(plotlyOutput("myplot"), image = "how to setup up path to custom image ?")`

I tried :
`withSpinner(plotlyOutput("myplot"), image = "C:/Users/john/Documents/myproject/mypic.gif")`
but its doesnt work.
Some help would be appreciated

**Comment by daattali** [comment]
The image is loaded using a regular HTML img tag. You need to work out the pathing so that you can load the image is shiny as a regular img tag. If it works in img, it'll work here too.

**Comment by learning-freak** [comment]
I used `shiny::tags$img(src = "mygif.gif",  width = "20%", height = "50px")` in mainpanel (for example) to display image and its works like charm. So I set up the path like this :
`withSpinner(plotlyOutput("myplot"), image = shiny::tags$img(src = "mygif.gif", width = "20%", height = "50px"))`
but i dont get result, i only get blank page with "Loading...". Here the full code


```
library(shiny)
library(shinycssloaders)

ui <- fluidPage(

    # Application title
    titlePanel("example"),

    mainPanel(
        shiny::tags$img(src = "mygif.gif", height = 100, width = 100), #displayed perfectly on app
        shinycssloaders::withSpinner(plotOutput("distPlot1")), #displayed perfectly on app
        shinycssloaders::withSpinner(plotOutput("distPlot2"), 
                                     image = shiny::tags$img(src = "mygif.gif", height = 100, width = 100)) #the gif is not displayed on app
    )
)


server <- function(input, output) {


    output$distPlot1 <- renderPlot({
        hist(rnorm(1000), main = "with Spinner : displayed perfectly")
    })
    
    output$distPlot2 <- renderPlot({
        hist(rnorm(1000), main = "with my custom gif : doesnt work")
    })
}

# Run the application 
shinyApp(ui = ui, server = server)
```

PS : You can download the gif here : https://media1.giphy.com/media/QWvra259h4LCvdJnxP/giphy.gif
How can we fix it ? Thanks in advance

**Comment by daattali** [comment]
That's strange, you shouldn't have to use `list(src=)`. You should just be able to use `image = path`.

If the image is located in a `www` folder or if it's used together with `addResourcePath()` it should just work

**Comment by learning-freak** [comment]
I put the image in a `www` folder and i used `list(src=)` and its works like charm

**Comment by daattali** [comment]
It should work without using list src. If you have a few minutes could you upload a ZIP of a directory that contains the app along with the image file with your directory structure, where it isn't working?

**Comment by learning-freak** [comment]
Yes, please see attachement
[example.zip](https://github.com/daattali/shinycssloaders/files/5599324/example.zip)

**Comment by daattali** [comment]
Your example works for me using `image = "mygif.gif"`. To be clear, you also need to ensure the working directory is set correctly, which means:
- you need the working directory to be the directory where `app.R` is located
- you need to run the app using `shiny::runApp()` or using the green "Run" button in RStudio (it won't work if you run the app by copying the code into the R console)

**Comment by learning-freak** [comment]
Okay, i didn't notice that. Thank you
