### ISSUE TITLE
Example of how to use custom CSS

### ISSUE THREAD

**Issue by jsicherman** [daattali/shinycssloaders#59]
Hi,

I want to use a different spinner, specifically [this one](https://codepen.io/drewendly/pen/ZBqazz), but I'm not sure how support for custom CSS is supposed to work and I don't see an example on your page. Do you have any advice on how to incorporate this?

Thanks!

**Comment by daattali** [comment]
To be honest I've never used the custom.css parameter and I'm not sure how to use it. Maybe @andrewsali , the original author, will chip in

**Comment by jsicherman** [comment]
Realized that enabling it simply disables the built-in CSS styles, rather than allowing you to specify your own. I ended up forking this to add support for custom HTML and specifying custom class names (#60)
