### ISSUE TITLE
Support messages in `withSpinner`

### ISSUE THREAD

**Issue by Nelson-Gon** [daattali/shinycssloaders#68]
Hello,

Great package. This is more of a feature request than bug report. In `withSpinner`, I would like to be able to add a message that says for example "Loading some very long processing time object" alongside the spinner. 

I think this could be done with a custom CSS but was wondering if there could be inbuilt support for this.

Thank you,

NelsonGon

**Comment by daattali** [comment]
Duplicate of #28
