### ISSUE TITLE
Infinite spinner on req(cancelOutput = TRUE)

### ISSUE THREAD

**Issue by bartekch** [daattali/shinycssloaders#71]
When there is an output with spinner and somewhere in its reactive dependencies the processing is stopped by `req(..., cancelOutput = TRUE)`, spinner will never disappear. In the following app this is happening when the box is unchecked and data is  recalculated. The previous output is still there, but the spinner won't hide back.

```r
library(shiny)
library(shinycssloaders)

shinyApp(
  ui = basicPage(
    checkboxInput("is_correct", "Is data correct?", TRUE),
    actionButton("recalculate", "Recalculate data"),
    
    shinycssloaders::withSpinner(
      tableOutput("table")
    )
  ),
  
  server = function(input, output, session) {
    output$table <- renderTable({
      input$recalculate
      Sys.sleep(1)
      req(isolate(input$is_correct), cancelOutput = TRUE)
      data.frame(x = rnorm(5))
    })
  }
)
```

I guess it could not be trivial to fix, but anyway, it would be nice to have spinner hidden in such cases.

**Comment by daattali** [comment]
Thanks for the report. After investigating the issue, I think it stems from the fact that shiny never triggers an "error" event when cancelOutput is used.

I filed an issue with shiny https://github.com/rstudio/shiny/issues/3787 and hopefully this will be fixed automatically when it's fixed in shiny.

**Comment by daattali** [comment]
I'm closing this issue because there's not much to do on our end. This will automatically be fixed when shiny fixes their bug.
