### ISSUE TITLE
"ui_element must be a Shiny tag" error when using plotlyOutput and DTOutput

### ISSUE THREAD

**Issue by ilaria-kode** [daattali/shinycssloaders#73]
Hi,

when using the latest version on github ( 26a6569bfcddce9ce7821db1caa1b945aa4b3ffe ) , I get this error

`ui_element must be a Shiny tag` 

on apps that were working fine with previous versions of the package and that use plotly or DT packages. 

A minimal reprex is this app:

```
library(shiny)
library(shinycssloaders)
library(plotly)

ui <- fluidPage(

    sidebarLayout(
        sidebarPanel(

        ),

        mainPanel(
           plotlyOutput("distPlot") %>% withSpinner()
        )
    )
)

server <- function(input, output) {

    output$distPlot <- renderPlotly({

      faithful %>%
        ggplot(aes(eruptions,waiting))+
        geom_point()
    })
}

# Run the application
shinyApp(ui = ui, server = server)
```

I believe the problem is caused by the fact that the withSpinner function is checking for inheritance on ` shiny.tag` while both plotlyOutput and DTOutput return objects with class ` shiny.tag.list` .

thank you,
Ilaria

**Comment by daattali** [comment]
Thanks for reporting and for doing the extra work of finding the cause!
