### ISSUE TITLE
Demo Error

### ISSUE THREAD

**Issue by Fokn** [daattali/shinycssloaders#74]
I'm firstly using your package to upgrade a shiny app of mine and wanted to check out other styles.

Unfortunately the Demo linked via https://daattali.com/shiny/shinycssloaders-demo/  throws an error:

> An error has occurred!
> 
> An error has occurred. Check your logs or contact the app author for clarification.

Best Regards, Patrick

**Comment by daattali** [comment]
Thanks for the report! The shiny server hosting this app (and others) has inexplicably gone down and for the first time in 7 years I'm not able to revive it quickly. Will have to investigate. I'm closing this issue since it's not really an issue with the package, but thank you!
