### ISSUE TITLE
Texts are centered in the output when using an image as a spinner.

### ISSUE THREAD

**Issue by YonghuiDong** [daattali/shinycssloaders#79]
Hi Dean Attali,

Thanks a lot for this great package. 

I find out that the texts are centered in the output when using an image  in`withSpinner()` function.

Please see the example below (Sorry the image is not shown properly). How can I left align the output text?

Thanks lot.

Dong

```r
library(shiny)

ui <- fluidPage(
  actionButton("go", "Go"),
  shinycssloaders::withSpinner(
    verbatimTextOutput("test"), 
    image = "https://imgur.com/gallery/XUomVWX"
  )
)
server <- function(input, output) {
  output$test <- renderPrint({
    input$go
    Sys.sleep(1.5)
    cat("R version 4.2.2 (2022-10-31) 
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: aarch64-apple-darwin20 (64-bit)")
  })
}
shinyApp(ui, server)
```

**Comment by daattali** [comment]
Thanks for providing a reproducible example! This is indeed a bug that I never noticed. I'll take a look when I can.

**Comment by daattali** [comment]
Should be fixed now, please test it and let me know if it works or not for you.

**Comment by YonghuiDong** [comment]
It works perfectly now. 

Thanks a lot!

Dong

**Comment by daattali** [comment]
I see you live in my home country! Shabbat shalom :)

**Comment by YonghuiDong** [comment]
@daattali,

Wow, I did not realize that you are Israeli. Shabbat shalom to you as well.

Dong
