### ISSUE TITLE
hideSpinner(), showSpinner() missing in CRAN repository?

### ISSUE THREAD

**Issue by kd-chicago** [daattali/shinycssloaders#86]
ls("package:shinycssloaders") output is
"withSpinner" - no other functions seems to be available

When running Shiny app, getting error:
Error in hideSpinner: could not find function "hideSpinner"

using 'withSpinner()' has no issues, it works.

The package was installed with standard 'install.packages("shinycssloaders")
from url:
_trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/shinycssloaders_1.0.0.zip'
Content type 'application/zip' length 140848 bytes (137 KB)
downloaded 137 KB_
packageVersion gives '1.0.0'

When installed with 
remotes::install_github("daattali/shinycssloaders")
packageVersion() output is  ‘1.0.0.9011’ 
and  ls("package:shinycssloaders") output is
[1] "hidePageSpinner" "hideSpinner"     "showPageSpinner" "showSpinner"     "withSpinner"  

So  CRAN repository has outdated version with missing important functions.

R 4.2.1, RStudio 2022.07.1 Build 554, Windows 10

**Comment by daattali** [comment]
These functions are relatively new and are still being beta tested, it's not on CRAN yet. You can use https://cranalerts.com/ to get notified when it goes on CRAN
