### ISSUE TITLE
withSpinner()'s documented caption argument not available in CRAN installation

### ISSUE THREAD

**Issue by scconner7** [daattali/shinycssloaders#87]
The `caption` argument to `withSpinner()` detailed in the README [here](https://github.com/daattali/shinycssloaders#add-a-message) is not available in the CRAN installation of the package.

I can utilize the developer installation for the time being, but it would be great to see this feature included in the CRAN installation as well. Is there any intention to update the CRAN version to the version that includes the `caption` argument? If so, any estimated timeline on when we could expect to see it included there?

**Comment by daattali** [comment]
The documentation on GitHub refers to the Github (dev) version. There is no specific ETA for the release yet, as there are still a couple of issues I am trying to think of solutions for before releasing. I also manage many other packages so I need to be strategic about timing them all together. If you'd like to be notified when it is released, you can sign up for notifications on https://cranalerts.com/

Closing this issue, feel free to open one if there's a bug or feature request
