### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by nick-youngblut** [daattali/shinycssloaders#90]
It appears that there has been [a lot of work done on shinycssloaders](https://github.com/daattali/shinycssloaders/commits/master) in the past months, but the last release ([v1.0.0](https://github.com/daattali/shinycssloaders/releases/tag/1.0.0)) was released in 2020. Are there plans on creating a new (GitHub/CRAN) release?

**Comment by daattali** [comment]
Yes it will be released soon. Some of the recent changes are still not 100% stable and are still being beta tested, I try to caution on the side of being conservative and slower with releases.

**Comment by daattali** [comment]
The new version (1.1.0) is now on CRAN.

A project I'm working on for a client of mine requires the updated version, so that prompted me to hurry up with the testing of the new features :)
