### ISSUE TITLE
showSpinner() function not found

### ISSUE THREAD

**Issue by alex-silverman** [daattali/shinycssloaders#91]
The showSpinner() function isn't found. 

When I run `getNamespaceExports("shinycssloaders")`:
[1] "withSpinner"

When I run `shinycssloaders::showSpinner()`:
Error: 'showSpinner' is not an exported object from 'namespace:shinycssloaders'

`withSpinner()` works just fine.

**Comment by fredjaya** [comment]
Same here, `showPageSpinner()` missing too

**Comment by daattali** [comment]
You are probably not using the development version. These functions are not on CRAN yet. 

Install the development version to use these features: 

```
remotes::install_github("daattali/shinycssloaders")
```
