### ISSUE TITLE
No showPageSpinner function Error

### ISSUE THREAD

**Issue by hlblade** [daattali/shinycssloaders#93]
When I try to run the demo code, I get a No showPageSpinner function Error.
`library(shiny)
library(shinycssloaders)

ui <- fluidPage(
  actionButton("go", "Go"),
  plotOutput("plot")
)
server <- function(input, output) {
  observeEvent(input$go, {
    showPageSpinner()
    Sys.sleep(1)
    hidePageSpinner()
  })
  output$plot <- renderPlot({
    plot(runif(10))
  })
}
shinyApp(ui, server)`

**Comment by daattali** [comment]
Are you sure you're using the latest version of the package?

**Comment by daattali** [comment]
@hlblade what version of shinycssloaders are you using?

**Comment by hlblade** [comment]
I was previously using version 1.0.0 and just found out that the latest version is 1.1.0. After updating, everything is running smoothly. Please forgive my carelessness and thanks very much for your great work. I wish you all the best.
